DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${SERVICE_APP_USER}') THEN
        EXECUTE format(
            'CREATE ROLE %I LOGIN PASSWORD %L',
            '${SERVICE_APP_USER}',
            '${SERVICE_APP_PASSWORD}'
        );
    ELSE
        EXECUTE format(
            'ALTER ROLE %I WITH LOGIN PASSWORD %L',
            '${SERVICE_APP_USER}',
            '${SERVICE_APP_PASSWORD}'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${LAW_APP_USER}') THEN
        EXECUTE format(
            'CREATE ROLE %I LOGIN PASSWORD %L',
            '${LAW_APP_USER}',
            '${LAW_APP_PASSWORD}'
        );
    ELSE
        EXECUTE format(
            'ALTER ROLE %I WITH LOGIN PASSWORD %L',
            '${LAW_APP_USER}',
            '${LAW_APP_PASSWORD}'
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DEV_ADMIN_USER}') THEN
        EXECUTE format(
            'CREATE ROLE %I LOGIN PASSWORD %L SUPERUSER CREATEDB CREATEROLE INHERIT',
            '${DEV_ADMIN_USER}',
            '${DEV_ADMIN_PASSWORD}'
        );
    ELSE
        EXECUTE format(
            'ALTER ROLE %I WITH LOGIN PASSWORD %L SUPERUSER CREATEDB CREATEROLE INHERIT',
            '${DEV_ADMIN_USER}',
            '${DEV_ADMIN_PASSWORD}'
        );
    END IF;
END
$$;

REVOKE ALL ON SCHEMA service FROM PUBLIC;
REVOKE ALL ON SCHEMA legal_rag FROM PUBLIC;

GRANT USAGE ON SCHEMA service TO ${SERVICE_APP_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA service TO ${SERVICE_APP_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA service TO ${SERVICE_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA service
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SERVICE_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA service
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${SERVICE_APP_USER};

GRANT USAGE ON SCHEMA legal_rag TO ${LAW_APP_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA legal_rag TO ${LAW_APP_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA legal_rag TO ${LAW_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA legal_rag
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${LAW_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA legal_rag
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${LAW_APP_USER};

REVOKE ALL ON SCHEMA legal_rag FROM ${SERVICE_APP_USER};
REVOKE ALL ON SCHEMA service FROM ${LAW_APP_USER};

SET LOCAL search_path TO service, public;
